In [1]:
import pandas as pd
dic = {
    'food':['KFC','McDonald','SchoolFood'],
    'price':[1000,2000,2500],
    'rating':[4.5,3.9,4.2]
}
df = pd.DataFrame(dic)
df

         food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [2]:
df[['food','rating']]

         food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

In [3]:
df = df.rename(columns={'food':'place'})
df

        place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2