# 타이타닉 데이터 실습

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

- PassengerID: 각 승객에게 주어진 고유 ID 번호  
- Survived: 생존 여부(0=사망, 1=생존) => Target 데이터(종속변수)->y=ax+bz+c ->독립변수,데이터     
- Pclass: 티켓 클래스(1=1등석, 2=2등석, 3=3등석)  
- Sex: 성별  
- Age: 나이  
- SibSp: 형제자매/배우자의 수  
- Parch: 함께 탑승한 부모님/아이들의 수  
- Ticket: 티켓 번호  
- Fare: 탑승 요금  
- Cabin: 수하물 번호 또는 객실 카테고리   
- Embarked: 선착장(C=Cherbourg, Q=Queenstown,S=Southampton)

In [3]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [9]:
df['Pclass'].corr(df['Fare'])

np.float64(-0.5494996199439082)

In [10]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [11]:
df.select_dtypes(include='number').corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [12]:
df[['SibSp','Parch','Fare']].corr()

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [13]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [14]:
df.std(numeric_only=True)

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [15]:
df.groupby('Survived').mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [16]:
 df.groupby(['Sex','Survived']).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [17]:
df1 = df.rename({"Name":"이름"},axis=1)
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [18]:
df2 = df.rename(columns={'Age':'나이'})
df2.head(1)

,PassengerId,Survived,Pclass,Name,Sex,나이,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [19]:
df3 = df.Sex.map(lambda x : 0 if x == "female" else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [20]:
def n_square(x):
    return x ** 2

In [21]:
df4_1 = df['Age'].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [22]:
def n_square(x, n):
    return x ** n

In [23]:
df4 = df[['Age','SibSp','Fare']].apply(n_square,n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

# 객체 연산

In [24]:
data = [[1,10,100],[2,20,200],[3,30,300]]
col = ['col1','col2','col3']
row = ['row1','row2','row3']
df = pd.DataFrame(data=data,index=row,columns=col)
df

      col1  col2  col3
row1     1    10   100
row2     2    20   200
row3     3    30   300

In [25]:
result = df.add(1)
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [26]:
result = df+1
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [27]:
data2 = [[3],[4],[5]]
df2 = pd.DataFrame(data=data2,index=['row1','row2','row3'],columns=['col1'])
df2

      col1
row1     3
row2     4
row3     5

In [28]:
result = df.add(df2)
result

      col1  col2  col3
row1     4   NaN   NaN
row2     6   NaN   NaN
row3     8   NaN   NaN

In [29]:
result = df.add(df2,fill_value=0)     # df2에 없는 컬럼에 0을 채워서 연산
result

      col1  col2   col3
row1     4  10.0  100.0
row2     6  20.0  200.0
row3     8  30.0  300.0

In [30]:
result = df.add(1)  # sub(), mul(), div(), 나머지연산 mod()
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [31]:
col = ['col1','col2']
row = ['row1','row2']
data1 = [[1,2],[3,4]]
data2 = [[5,6],[7,8]]
df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [32]:
df1

   0  1
0  1  2
1  3  4

In [33]:
df2

   0  1
0  5  6
1  7  8

In [34]:
df3 = df1.dot(df2)
df3

    0   1
0  19  22
1  43  50

In [35]:
import numpy as np
col = ['col1','col2','col3']
row = ['row1','row2','row3']
data = np.random.rand(3,3) * 100
df = pd.DataFrame(data=data, index=row, columns=col)
df

           col1       col2       col3
row1  33.284776  95.793082  74.588707
row2   3.673698  29.446603  53.521707
row3  46.912454   1.968549  40.014506

In [36]:
df.round(0)

      col1  col2  col3
row1  33.0  96.0  75.0
row2   4.0  29.0  54.0
row3  47.0   2.0  40.0

In [37]:
df.round(2)

       col1   col2   col3
row1  33.28  95.79  74.59
row2   3.67  29.45  53.52
row3  46.91   1.97  40.01

In [38]:
import numpy as np
col = ['col1','col2','col3']
row = ['row1','row2','row3']
data = [[1,2,3],[4,5,6],[7,np.nan,9]]
df = pd.DataFrame(data=data, index=row, columns=col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [39]:
df.sum(axis=0)

col1    12.0
col2     7.0
col3    18.0
dtype: float64

In [40]:
df.sum(axis=1)

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [41]:
df.sum(axis=0,skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [42]:
df.prod(axis=0)

col1     28.0
col2     10.0
col3    162.0
dtype: float64

In [43]:
df.prod(axis=1)

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [44]:
df.prod(axis=0,skipna=False)

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [45]:
df.transpose()

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [46]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [47]:
idx = ['A','A','B','B','B','C','C','C','D','D','D','D','E','E','E']
col = ['col1','col2','col3']
data = np.random.randint(0,9,(15,3))
df = pd.DataFrame(data=data,index=idx,columns=col).reset_index()
df

   index  col1  col2  col3
0      A     6     5     5
1      A     2     0     4
2      B     3     6     7
3      B     0     1     6
4      B     3     1     6
5      C     4     2     8
6      C     6     7     7
7      C     8     2     2
8      D     0     5     7
9      D     7     3     6
10     D     5     1     3
11     D     3     4     0
12     E     0     8     2
13     E     3     1     1
14     E     1     2     6

In [48]:
df.groupby('index').mean()

           col1      col2      col3
index
A      4.000000  2.500000  4.500000
B      2.000000  2.666667  6.333333
C      6.000000  3.666667  5.666667
D      3.750000  3.250000  4.000000
E      1.333333  3.666667  3.000000

In [49]:
df.groupby('index').count()

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [50]:
df.groupby('index').agg(['sum','mean'])

      col1           col2           col3
       sum      mean  sum      mean  sum      mean
index
A        8  4.000000    5  2.500000    9  4.500000
B        6  2.000000    8  2.666667   19  6.333333
C       18  6.000000   11  3.666667   17  5.666667
D       15  3.750000   13  3.250000   16  4.000000
E        4  1.333333   11  3.666667    9  3.000000

In [51]:
period = pd.period_range(start='2022-01-13 00:00:00', end='2022-01-13 02:30:00',freq='30min')
data = {'col1':[1,2,3,4,5,6],'col2':period}
idx = ['row1','row2','row3','row4','row5','row6']
df = pd.DataFrame(data=data,index=idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [52]:
df.rolling(window=3).sum(numeric_only=True)     #앞의 3개의 누적합

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [53]:
df.rolling(window=3).mean(numeric_only=True)  #앞의 3개의 평균

      col1
row1   NaN
row2   NaN
row3   2.0
row4   3.0
row5   4.0
row6   5.0

# 객체 인덱싱

In [54]:
data = {
    '2015': [9904312, 3448737, 2890451, 2466052],
    '2010': [9631482, 3393191, 2632035, 2431774],
    '2005': [9762546, 3512547, 2517680, 2456016],
    '2000': [9853972, 3655437, 2466338, 2473990],
    '지역': ['수도권','경상권','수도권','경상권'],
    '2010-2015 증가율': [0.0283, 0.0163, 0.0982, 0.0141]
}

column_list = ['지역','2015','2010','2005','2000','2010-2015 증가율']
index_list = ['서울','부산','인천','대구']
df = pd.DataFrame(data,index=index_list, columns=column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [55]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [56]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [57]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='str')

In [58]:
df.index.name='도시'
df.columns.name='특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [59]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [60]:
df['지역']       #열이 먼저 그다음 행  df['서울']은 에러

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [61]:
df.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [62]:
df[['2010','2015']]

특성     2010     2015
도시
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [63]:
df[['지역']]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [64]:
type(df[['지역']])

pandas.DataFrame

In [65]:
type(df['지역'])

pandas.Series

In [66]:
import numpy as np
df2 = pd.DataFrame(np.arange(12).reshape(3,4))   # np.arange()와 range 함수는 동일하게 동작한다.
df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [67]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [70]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [71]:
df['2005-2010 증가율'] = ((df['2010'] - df['2005']) / df['2005'] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [72]:
del df['2010-2015 증가율']  # df.drop('2010-2015 증가율', axis=1)
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [73]:
df3 = df.drop('2005-2010 증가율', axis=1)
df3

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9631482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473990

In [74]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [75]:
df3 = df.drop('서울',axis=0)
df3

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [76]:
df['2015']['서울']

np.int64(9904312)

In [77]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [78]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [79]:
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [80]:
df[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [81]:
df.iloc[[0,2]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [82]:
df.iloc[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [83]:
df.loc[['서울','부산']]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [84]:
df.loc['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [85]:
df = pd.DataFrame({'A':[1,4,7], 'B':[2,5,8], 'C':[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [86]:
df.iloc[0]

A    1
B    2
C    3
Name: 0, dtype: int64

In [87]:
df.iloc[[0,2]]

   A  B  C
0  1  2  3
2  7  8  9

In [88]:
print(df.loc[0])

A    1
B    2
C    3
Name: 0, dtype: int64

In [89]:
df.loc[:,'A']

0    1
1    4
2    7
Name: A, dtype: int64

In [90]:
df.loc[:,'A':'B']

   A  B
0  1  2
1  4  5
2  7  8

In [91]:
df['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [92]:
#df[0] 열,행순서라 에러

In [93]:
df.loc[0]['B']

np.int64(2)

In [94]:
df['B'][0]

np.int64(2)