In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['row1','row2','row3'],columns=['col1','col2','col3'])
df

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [3]:
result = df.loc['row1']
result

col1    1
col2    2
col3    3
Name: row1, dtype: int64

In [4]:
result = df.loc[['row1','row3']]
result

      col1  col2  col3
row1     1     2     3
row3     7     8     9

In [5]:
result = df.loc['row2','col2']
result

np.int64(5)

In [6]:
result = df.loc['row1':'row3','col2']
result

row1    2
row2    5
row3    8
Name: col2, dtype: int64

In [7]:
bool2 = [False,True,False]
result = df.loc[bool2]
result

      col1  col2  col3
row2     4     5     6

In [8]:
result = df.loc[df['col3']>5]
result

      col1  col2  col3
row2     4     5     6
row3     7     8     9

In [9]:
result = df.loc[df['col3']>5,['col2']]
result

      col2
row2     5
row3     8

In [10]:
result = df.loc[lambda df : df['col2'] == 5]
result

      col1  col2  col3
row2     4     5     6

In [11]:
df.loc[['row1','row3'],['col3']]=10
df

      col1  col2  col3
row1     1     2    10
row2     4     5     6
row3     7     8    10

In [12]:
#df.loc[:,['col3']]='B'   # 타입 오류 발생, 데이터타입 자동변환해주지않음
#df

In [13]:
df['col3']='B'
df

      col1  col2 col3
row1     1     2    B
row2     4     5    B
row3     7     8    B

# 멀티 인덱스

In [14]:
index_tuples = [('row1','val1'),('row1','val2'),('row2','val1'),('row2','val2'),
               ('row2','val3'),('row3','val2'),('row3','val3')]
values = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21]]
index = pd.MultiIndex.from_tuples(index_tuples)  # 인덱스 설정
df = pd.DataFrame(values,columns=['col1','col2','col3'],index=index)
df

           col1  col2  col3
row1 val1     1     2     3
     val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18
     val3    19    20    21

In [15]:
result = df.loc['row2']
result

      col1  col2  col3
val1     7     8     9
val2    10    11    12
val3    13    14    15

In [16]:
result = df.loc[('row2','val2')]
result

col1    10
col2    11
col3    12
Name: (row2, val2), dtype: int64

In [17]:
result = df.loc[[('row2','val2')]]
result

           col1  col2  col3
row2 val2    10    11    12

In [18]:
result = df.loc[('row2','val2'),'col3']
result

np.int64(12)

In [19]:
result = df.loc[('row1','val2') : ('row3','val2')]
result

           col1  col2  col3
row1 val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18

In [20]:
data = [
    [100,900,800,700],
    [1200,1400,900,800]
]
columns = [
    ['영업이익','영업이익','당기순이익','당기순이익'],
    ['컨센서스','잠정치','컨센서스','잠정치']
]
index = ['2020/06','2020/09']
df = pd.DataFrame(data=data,index=index,columns=columns)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [21]:
data = [
    [100,900,800,700],
    [1200,1400,900,800]
]
level_0 = ['영업이익','당기순이익']
level_1 = ['컨센서스','잠정치']
idx = pd.MultiIndex.from_product([level_0,level_1])
index = ['2020/06','2020/09']
df = pd.DataFrame(data=data,index=index,columns=idx)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [22]:
import io

csv = '''
	A팀		B팀		C팀	
	삼성전자	카카오	삼성전자	카카오	삼성전자	카카오
2023-08-14	10	20	30	40	50	60
2023-08-16	20	20	30	40	50	60
2023-08-17	30	40	10	20	50	60
2023-08-18	30	40	10	20	50	60
2023-08-21	30	40	30	40	30	40
'''
df_csv = pd.read_csv(io.StringIO(csv),sep='\t',index_col=0,header=[0,1])
df_csv

,A팀,Unnamed: 2_level_0,B팀,Unnamed: 4_level_0,C팀,Unnamed: 6_level_0
,삼성전자,카카오,삼성전자,카카오,삼성전자,카카오
2023-08-14,10,20,30,40,50,60
2023-08-16,20,20,30,40,50,60
2023-08-17,30,40,10,20,50,60
2023-08-18,30,40,10,20,50,60
2023-08-21,30,40,30,40,30,40

In [23]:
df1 = df_csv.columns.to_frame(index=False).apply(lambda x : x.mask(x.str.contains('Unnamed'))).ffill()
df_csv = df_csv.set_axis(pd.MultiIndex.from_frame(df1, names=[''] * len(df_csv.columns[0])),axis=1)
df_csv

             A팀       B팀       C팀
           삼성전자 카카오 삼성전자 카카오 삼성전자 카카오
2023-08-14   10  20   30  40   50  60
2023-08-16   20  20   30  40   50  60
2023-08-17   30  40   10  20   50  60
2023-08-18   30  40   10  20   50  60
2023-08-21   30  40   30  40   30  40

In [24]:
df1

    0     1
0  A팀  삼성전자
1  A팀   카카오
2  B팀  삼성전자
3  B팀   카카오
4  C팀  삼성전자
5  C팀   카카오

In [25]:
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [26]:
df['영업이익']

         컨센서스   잠정치
2020/06   100   900
2020/09  1200  1400

In [27]:
df[[('영업이익','컨센서스')]]

         영업이익
         컨센서스
2020/06   100
2020/09  1200

In [28]:
df.loc['2020/06','영업이익']

컨센서스    100
잠정치     900
Name: 2020/06, dtype: int64

In [29]:
df.loc[['2020/06'],['영업이익']]

        영업이익
        컨센서스  잠정치
2020/06  100  900

In [30]:
df.loc['2020/06',('영업이익','컨센서스')]

np.int64(100)

In [31]:
# slice(None) : [:]슬라이스와 동일한 의미, 멀티 인덱스의 특정 레벨 내의 모든 값
df.loc['2020/06',(slice(None),'컨센서스')]

영업이익   컨센서스    100
당기순이익  컨센서스    800
Name: 2020/06, dtype: int64

In [32]:
df.loc[['2020/06'],(slice(None),'컨센서스')]

        영업이익 당기순이익
        컨센서스  컨센서스
2020/06  100   800

In [33]:
df2 = df.T
df2

            2020/06  2020/09
영업이익  컨센서스      100     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      잠정치       700      800

In [34]:
df2.loc[[('영업이익','컨센서스')]]

           2020/06  2020/09
영업이익 컨센서스      100     1200

In [35]:
df2.loc[('영업이익','컨센서스'),'2020/06']

np.int64(100)

In [36]:
df2.loc[[('영업이익','컨센서스')],'2020/06']

영업이익  컨센서스    100
Name: 2020/06, dtype: int64

In [37]:
df2.loc[[('영업이익','컨센서스')],['2020/06']]

           2020/06
영업이익 컨센서스      100

In [38]:
df2.loc[(slice(None),'컨센서스'),:]

            2020/06  2020/09
영업이익  컨센서스      100     1200
당기순이익 컨센서스      800      900

In [39]:
col1 = [1,2,3,4,5]
col2 = ['one','two','three','four','five']
col3 = [1.5,2.5,3.5,4.5,5.5]
col4 = [True,False,False,True,True]
df = pd.DataFrame({'col1':col1,'col2':col2,'col3':col3,'col4':col4})
df

   col1   col2  col3   col4
0     1    one   1.5   True
1     2    two   2.5  False
2     3  three   3.5  False
3     4   four   4.5   True
4     5   five   5.5   True

In [40]:
df.dtypes

col1      int64
col2        str
col3    float64
col4       bool
dtype: object

In [41]:
result = df.select_dtypes(include=float)
result

   col3
0   1.5
1   2.5
2   3.5
3   4.5
4   5.5

In [42]:
result = df.select_dtypes(include=[bool,float])
result

   col3   col4
0   1.5   True
1   2.5  False
2   3.5  False
3   4.5   True
4   5.5   True

In [43]:
result = df.select_dtypes(exclude=['int64'])
result

    col2  col3   col4
0    one   1.5   True
1    two   2.5  False
2  three   3.5  False
3   four   4.5   True
4   five   5.5   True

In [44]:
col = ['alpha','beta','gamma','delta','epsilon']
row = ['sigma','omega','lambda']
data = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
df = pd.DataFrame(data,row,col)
df

        alpha  beta  gamma  delta  epsilon
sigma       1     2      3      4        5
omega       6     7      8      9       10
lambda     11    12     13     14       15

In [45]:
df.filter(items=['alpha','delta'])

        alpha  delta
sigma       1      4
omega       6      9
lambda     11     14

In [46]:
df.filter(items=['omega'],axis=0)

       alpha  beta  gamma  delta  epsilon
omega      6     7      8      9       10

In [47]:
df.filter(like='ta')

        beta  delta
sigma      2      4
omega      7      9
lambda    12     14

In [48]:
df.filter(regex='[mn]')

        gamma  epsilon
sigma       3        5
omega       8       10
lambda     13       15

In [49]:
df.filter(regex='^g')    # ^ : 그 글자로 시작   regex:정규표현식

        gamma
sigma       3
omega       8
lambda     13

In [50]:
df.filter(regex='a$')    # $ : 그 글자로 종료

        alpha  beta  gamma  delta
sigma       1     2      3      4
omega       6     7      8      9
lambda     11    12     13     14

# 타이타닉

In [51]:
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [52]:
df.iloc[0:5,1:4]

   Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

In [53]:
df[['Name','Age','Sex','Survived']]

                                                  Name   Age     Sex  Survived
0                              Braund, Mr. Owen Harris  22.0    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female         1
2                               Heikkinen, Miss. Laina  26.0  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female         1
4                             Allen, Mr. William Henry  35.0    male         0
..                                                 ...   ...     ...       ...
886                              Montvila, Rev. Juozas  27.0    male         0
887                       Graham, Miss. Margaret Edith  19.0  female         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female         0
889                              Behr, Mr. Karl Howell  26.0    male         1
890                                Dooley, Mr. Patrick  32.0    male         0

[891 rows x 4 columns]

In [54]:
mask = (df['Sex'] == 'female')
mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [55]:
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [56]:
df9 = df[df['PassengerId'] == 3]['Name']
df9

2    Heikkinen, Miss. Laina
Name: Name, dtype: str

In [57]:
df9.values

<StringArray>
['Heikkinen, Miss. Laina']
Length: 1, dtype: str

In [58]:
df['family'] = df['SibSp'] + df['Parch']
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1

# 인덱스 설정

In [59]:
df = pd.DataFrame({'A':[1,4,7],'B':[2,5,8],'C':[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [60]:
df = df.set_index('A')
df

   B  C
A
1  2  3
4  5  6
7  8  9

In [61]:
df = pd.DataFrame(data=np.array([[1,2,3],[4,5,6],[7,8,9]]),
                  columns = [48,49,50])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9

In [62]:
a = pd.DataFrame(data=[[1,2,3]],columns=[48,49,50])
a

   48  49  50
0   1   2   3

In [63]:
df = pd.concat([df,a])   # append는 사용종료
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
0   1   2   3

In [64]:
df2 = df.reset_index(drop=True)
df2

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
3   1   2   3

In [65]:
df2 = df.reset_index(drop=False)
df2

   index  48  49  50
0      0   1   2   3
1      1   4   5   6
2      2   7   8   9
3      0   1   2   3

In [66]:
df = pd.DataFrame(data=np.array([[1,2,3],[4,5,6],[7,8,9]]),
                  columns=['A','B','C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [67]:
df2 = df.drop('A',axis=1,inplace=False)
df2

   B  C
0  2  3
1  5  6
2  8  9

In [68]:
df.drop('A',axis=1,inplace=True)
df

   B  C
0  2  3
1  5  6
2  8  9

In [69]:
df.drop('B',axis=1)
df

   B  C
0  2  3
1  5  6
2  8  9

In [70]:
df.drop(2,axis=0,inplace=True)
df

   B  C
0  2  3
1  5  6

In [71]:
df = pd.DataFrame(data=np.array([[1,2,3],[4,5,6],[7,8,9]]),
                  columns=['A','B','C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [72]:
df2 = df.drop([0,2],axis=0,inplace=False)
df2

   A  B  C
1  4  5  6

In [73]:
df2 = df.drop(['A','C'],axis=1,inplace=False)
df2

   B
0  2
1  5
2  8

In [74]:
df = pd.DataFrame(data=np.array([[1,2,3],[4,5,6],[7,8,9],[40,50,60],[23,35,37]]),
                  index = [2.5,12.6,4.8,4.8,2.5],
                  columns=[48,49,50])
df

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [75]:
df = df.reset_index()
df

   index  48  49  50
0    2.5   1   2   3
1   12.6   4   5   6
2    4.8   7   8   9
3    4.8  40  50  60
4    2.5  23  35  37

In [76]:
df2 = df.drop_duplicates(subset='index',keep='last').set_index('index')
df2

       48  49  50
index
12.6    4   5   6
4.8    40  50  60
2.5    23  35  37

In [78]:
df2 = df.drop_duplicates(subset='index',keep='first').set_index('index')
df2

       48  49  50
index
2.5     1   2   3
12.6    4   5   6
4.8     7   8   9

In [79]:
df2 = df.drop_duplicates(subset='index',keep=False).set_index('index')
df2

       48  49  50
index
12.6    4   5   6

In [80]:
df = pd.DataFrame(data=np.array([[1,2,3],[1,5,6],[7,8,9]]),
                  columns=['A','B','C'],index=[11,22,33])
df

    A  B  C
11  1  2  3
22  1  5  6
33  7  8  9

In [81]:
df.index[1]

np.int64(22)

In [85]:
df2 = df.drop(df.index[1],axis=0)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [84]:
df2 = df.drop(22)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [87]:
col = ['col1','col2','col3','col4','col5']
row = ['row1','row2','row3','row4']
data = [[1,2,3,pd.NA,5],[6,pd.NA,8,pd.NA,10],[11,12,13,14,15],[pd.NA,pd.NA,pd.NA,pd.NA,pd.NA]]
df = pd.DataFrame(data,row,col)
df

      col1  col2  col3  col4  col5
row1     1     2     3  <NA>     5
row2     6  <NA>     8  <NA>    10
row3    11    12    13    14    15
row4  <NA>  <NA>  <NA>  <NA>  <NA>

In [88]:
df2 = df.dropna(axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [89]:
df2 = df.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [row1, row2, row3, row4]

In [90]:
df2 = df.dropna(how='any',axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [91]:
df2 = df.dropna(how='all',axis=0)
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [92]:
df2 = df.dropna(thresh=3)    # 유효데이터가 3개 이상있으면 NA가 있더라도 남김
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [93]:
df2 = df.dropna(thresh=4)
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [94]:
df2 = df.dropna(subset=['col1','col2'])
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [95]:
df.dropna(subset=['col1','col2'],inplace = True)
df

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [96]:
col = ['col1','col2','col3','col4','col5']
row = ['row1','row2','row3','row4','row5']
na = np.nan
data = [[na, 2, na, 4, na],
        [6, 7, na, 9, na],
        [11,na, na, 14,15],
        [na,17,na,na,20],
        [na,22,na,na,25]]
df = pd.DataFrame(data,row,col)
df

      col1  col2  col3  col4  col5
row1   NaN   2.0   NaN   4.0   NaN
row2   6.0   7.0   NaN   9.0   NaN
row3  11.0   NaN   NaN  14.0  15.0
row4   NaN  17.0   NaN   NaN  20.0
row5   NaN  22.0   NaN   NaN  25.0

In [97]:
df2 = df.fillna('A')
df2

      col1  col2 col3  col4  col5
row1     A   2.0    A   4.0     A
row2   6.0   7.0    A   9.0     A
row3  11.0     A    A  14.0  15.0
row4     A  17.0    A     A  20.0
row5     A  22.0    A     A  25.0

In [100]:
dict = {'col1':'A','col2':'B','col3':'C','col4':'D','col5':'E'}
df.fillna(value=dict)

      col1  col2 col3  col4  col5
row1     A   2.0    C   4.0     E
row2   6.0   7.0    C   9.0     E
row3  11.0     B    C  14.0  15.0
row4     A  17.0    C     D  20.0
row5     A  22.0    C     D  25.0

In [101]:
df['col1'].fillna(100)

row1    100.0
row2      6.0
row3     11.0
row4    100.0
row5    100.0
Name: col1, dtype: float64

# Merge

In [102]:
df1 = pd.DataFrame({'고객번호':[1001,1002,1003,1004,1005,1006,1007],
                    '이름': ['둘리','도우너','또치','길동','희동','마이콜','영희']},
                   columns=['고객번호','이름'])
df1

   고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [106]:
df2 = pd.DataFrame({'고객번호':[1001,1001,1005,1006,1008,1001],
                    '금액': [10000,20000,15000,5000,10000,30000]},
                   columns=['고객번호','금액'])
df2

   고객번호     금액
0  1001  10000
1  1001  20000
2  1005  15000
3  1006   5000
4  1008  10000
5  1001  30000

In [107]:
df3 = pd.merge(df1,df2)    # 기본: inner, 교집합과 비슷
df3

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [108]:
df4 = pd.merge(df1,df2,how='outer')
df4

   고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN
9  1008  NaN  10000.0

In [109]:
df5 = pd.merge(df1,df2,how='left')
df5

   고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN

In [110]:
df6 = pd.merge(df1,df2,how='right')
df6

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1005   희동  15000
3  1006  마이콜   5000
4  1008  NaN  10000
5  1001   둘리  30000

In [111]:
df1 = pd.DataFrame({
    '품종':['setosa','setosa','virginica','virginica'],
    '꽃잎길이':[1.4,1.3,1.5,1.3]},
    columns=['품종','꽃잎길이'])
df1

          품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [112]:
df2 = pd.DataFrame({
    '품종':['setosa','virginica','virginica','versicolor'],
    '꽃잎너비':[0.4,0.3,0.5,0.3]},
    columns=['품종','꽃잎너비'])
df2

           품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [113]:
df3 = pd.merge(df1,df2)
df3

          품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [114]:
df1 = pd.DataFrame({
    '고객명':['춘향','춘향','몽룡'],
    '날짜':['2018-01-01','2018-01-02','2018-01-01'],
    '데이터':['20000','30000','100000']})
df1

  고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [115]:
df2 = pd.DataFrame({
    '고객명':['춘향','몽룡'],
    '데이터':['여자','남자']})
df2

  고객명 데이터
0  춘향  여자
1  몽룡  남자

In [116]:
df3 = pd.merge(df1,df2,on='고객명')    # on : 기준열을 지정, 서로다른 성격의 데이터열이 중복될때
df3

  고객명          날짜   데이터_x 데이터_y
0  춘향  2018-01-01   20000    여자
1  춘향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [118]:
df1 = pd.DataFrame({
    '이름':['춘향','춘향','몽룡'],
    '날짜':['2018-01-01','2018-01-02','2018-01-01'],
    '데이터':['20000','30000','100000']})
df1

   이름          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [119]:
df2 = pd.DataFrame({
    '성명':['춘향','몽룡'],
    '데이터':['여자','남자']})
df2

   성명 데이터
0  춘향  여자
1  몽룡  남자

In [121]:
df3 = pd.merge(df1,df2,left_on='이름',right_on='성명')
df3

   이름          날짜   데이터_x  성명 데이터_y
0  춘향  2018-01-01   20000  춘향    여자
1  춘향  2018-01-02   30000  춘향    여자
2  몽룡  2018-01-01  100000  몽룡    남자

In [122]:
df1 = pd.DataFrame({'도시':['서울','서울','서울','부산','부산'],
                    '연도':[2000,2005,2010,2000,2005],
                    '인구':[9853972,9762546,9631482,3655437,3512547]})
df1

   도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [123]:
df2 = pd.DataFrame(np.arange(12).reshape((6,2)),
                   index=[['부산','부산','서울','서울','서울','서울'],
                          [2000,2005,2000,2005,2010,2015]],
                   columns=['데이터1','데이터2'])
df2

         데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [124]:
df3 = pd.merge(df1,df2,left_on=['도시','연도'],right_index=True)
df3

   도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [126]:
df1 = pd.DataFrame(
    [[1.,2.],[3.,4.],[5.,6.]],
    index=['a','c','e'],
    columns=['서울','부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [127]:
df2 = pd.DataFrame(
    [[7.,8.,],[9.,10.],[11.,12.],[13,14]],
    index=['b','c','d','e'],
    columns=['대구','광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [128]:
df3 = pd.merge(df1,df2,how='outer',left_index=True,right_index=True)
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [129]:
df3 = pd.merge(df1,df2,left_index=True,right_index=True)
df3

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0